<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class roomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('room')->insert([
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C701',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C702',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C703',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C704',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C705',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C706',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C707',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C708',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C709',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C710',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C711',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C712',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C713',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C714',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C601',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C602',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C603',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C604',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C605',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C606',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C607',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C608',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C609',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C610',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C611',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C612',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C613',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C614',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Energy Conversion Lab',
                'room_id' => 'C501',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Electrical Circuits Lab',
                'room_id' => 'C502',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Ergonomics Lab',
                'room_id' => 'C503',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Electronics Lab',
                'room_id' => 'C504',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Hardware Networking Lab',
                'room_id' => 'C505',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Industrial Automation and Robotics Lab',
                'room_id' => 'C506',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Eco Comm Lab',
                'room_id' => 'C508',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'IE Methods Lab',
                'room_id' => 'C509',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'L301',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'L302',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Drafting Room/Lab',
                'room_id' => 'L303',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Drafting Room/Lab',
                'room_id' => 'L304',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Physics Lab',
                'room_id' => 'L305',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Dispensing Room 1/Lab',
                'room_id' => 'L306',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Dispensing Room 2/Lab',
                'room_id' => 'L307',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Chemistry Lab',
                'room_id' => 'A308',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Photo Video Studio',
                'room_id' => 'C301',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Computer Lab',
                'room_id' => 'C302',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'C303',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Fine Arts Studio',
                'room_id' => 'C304',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Drafting Room/Lab',
                'room_id' => 'C305',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Drafting Room/Lab',
                'room_id' => 'C306',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Drawing Room',
                'room_id' => 'C308',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Computer Lab',
                'room_id' => 'L201',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'MAC Lab',
                'room_id' => 'L202',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Computer Lab',
                'room_id' => 'L203',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Computer Lab',
                'room_id' => 'L204',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Aeronautical Lab',
                'room_id' => 'L205',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Aeronautical Lab',
                'room_id' => 'L206',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Safety Lab',
                'room_id' => 'L207',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Regular Lecture Room',
                'room_id' => 'L208',
                'room_type' => 'Lecture',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Computer Lab',
                'room_id' => 'C201',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Computer Lab',
                'room_id' => 'C202',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Computer Lab',
                'room_id' => 'C203',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Cisco Networking Lab',
                'room_id' => 'C204',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'HVAC LAB',
                'room_id' => 'L101',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Surveying LAB',
                'room_id' => 'L102',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Soil Mechanics and Testing Lab',
                'room_id' => 'L103',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Machine Shop',
                'room_id' => 'L104',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Aeronautical Lab',
                'room_id' => 'L105',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Hydraulics Lab',
                'room_id' => 'L106',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'Steam Powerplant Lab',
                'room_id' => 'L107',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
            [
                'room_name' => 'ME/CE Dispensing Room',
                'room_id' => 'L108',
                'room_type' => 'Laboratory',
                'building' => 'COECSA',
                'pref_class' => 'None',
            ],
        ]);
    }
}
